In [2]:
import numpy as np

## Implementation of a polynomial function with variable degree

The basic version

In [16]:
def polyfun(coeffs, x):
    res = 0
    for i in range(len(coeffs)):
        res += coeffs[i] * (x**i)
    return res

Check that it works

In [17]:
polyfun([0,0,1],2)

4

In [57]:
test = lambda x: 1.5 + 2.1*x - 1.1*x**2 + 5.21*x**3
print(test(1.3))
print(polyfun([1.5, 2.1, -1.1, 5.21], 1.3))

13.81737
13.81737


A short version using ``sum()``

In [60]:
def polyfun2(coeffs, x):
    return sum(coeffs[i]*x**i for i in range(len(coeffs)))

In [61]:
print(polyfun2([1.5, 2.1, -1.1, 5.21], 1.3))

13.81737


Let's do it in one line

In [1]:
polyfun3 = lambda coeffs, x: sum(coeffs[i]*x**i for i in range(len(coeffs)))

print(polyfun3([1.5, 2.1, -1.1, 5.21], 1.3))

13.81737


Instead of passing the argument ``x`` for direct evaluation we can also write a function ``polygen()`` that returns the desired polynomial as a function

In [5]:
def polygen(coeffs):
    return lambda x: sum(coeffs[i]*x**i for i in range(len(coeffs)))

In [7]:
degree3fun = polygen([1.5, 2.1, -1.1, 5.21])

print(degree3fun(1.3))

13.81737


## Boolean masking

In [3]:
testarray = np.arange(-2, 3)
print(testarray)

[-2 -1  0  1  2]


In [4]:
mask = testarray>=0
print(mask)

[False False  True  True  True]


In [15]:
print(testarray[mask])

[0 1 2]


We can emulate this using a list comprehension

In [14]:
print(np.array([x for x in testarray if x>=0]))

[0 1 2]


In [21]:
print(testarray[[True,False,True,False,False]])

[-2  0]


## Pandas

Below we import pandas (one of the main python libraries for data analysis) and use it to read a csv file into a DataFrame, which is the primary data structure of pandas. You are invited to familiarize yourself with the DataFrame structure via the [pandas documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html).

In [1]:
import pandas as pd

In [4]:
pd.DataFrame?

https://catalog.data.gov/dataset

In [64]:
census_df = pd.read_csv('Census.csv')

In [65]:
census_df

StateAbbr        PlaceName  PlaceFIPS  Population2010  ACCESS2_CrudePrev  \
0          CA           Folsom     624638           72203                7.5   
1          FL            Largo    1239425           77648               19.6   
2          CA         Berkeley     606000          112580                7.7   
3          CA             Napa     650258           76915               12.3   
4          FL          Sunrise    1269700           84439               22.8   
5          FL   Pembroke Pines    1255775          154750               21.4   
6          NJ          Trenton    3474000           84913               25.4   
7          CO           Pueblo     862000          106595               19.9   
8          WI           Racine    5566000           78860               16.6   
9          WA           Auburn    5303180           70180               12.2   
10         TX           Austin    4805000          790390               20.6   
11         IL         Waukegan    1779293           89078               23.3   
12         MN    Brooklyn Park    2707966           75781                9.9   
13         WA           Renton    5357745           90927               11.0   
14         OK    Oklahoma City    4055000          579999               18.7   
15         GA          Augusta    1304204          195844               21.2   
16         MA      Springfield    2567000          153060               15.9   
17         CA      Bakersfield     603526          347483               16.4   
18         LA     Lake Charles    2241155           71993               17.0   
19         IL       Schaumburg    1768003           74227                8.5   
20         TN      Clarksville    4715160          132929               15.5   
21         FL            Miami    1245000          399457               36.2   
22         WI        Green Bay    5531000          104057               13.6   
23         SD      Sioux Falls    4659020          153888               11.3   
24         CO          Greeley     832155           92889               17.4   
25         CA          Visalia     682954          124442               15.1   
26         TX        Arlington    4804000          365438               22.1   
27         IA        Davenport    1919000           99685                8.9   
28         TX       Round Rock    4863500           99887               18.1   
29         CA        Sunnyvale     677000          140081                7.8   
..        ...              ...        ...             ...                ...   
470        MN      Minneapolis    2743000          382578               10.5   
471        AR       Fort Smith     524550           86209               15.8   
472        CO           Arvada     803455          106433                9.6   
473        IL          Decatur    1718823           76122               12.7   
474        NJ        Elizabeth    3421000          124969               26.1   
475        CA        Vacaville     681554           92428               10.3   
476        CA       Costa Mesa     616532          109960               12.5   
477        KS         Lawrence    2038900           87643               13.7   
478        CA        Fairfield     623182          105321               12.3   
479        UT            Sandy    4967440           87461                9.8   
480        CA    San Francisco     667000          805235                8.8   
481        FL  West Palm Beach    1276600           99919               23.7   
482        ID       Boise City    1608830          205671               14.5   
483        CA      Westminster     684550           89701               13.7   
484        OR        Beaverton    4105350           89803               10.8   
485        CA           Downey     619766          111772               17.5   
486        MS          Jackson    2836000          173514               21.9   
487        ID            Nampa    1656260           81557               23.0   
488 

In [67]:
census_df["StateAbbr"]

0      CA
1      FL
2      CA
3      CA
4      FL
5      FL
6      NJ
7      CO
8      WI
9      WA
10     TX
11     IL
12     MN
13     WA
14     OK
15     GA
16     MA
17     CA
18     LA
19     IL
20     TN
21     FL
22     WI
23     SD
24     CO
25     CA
26     TX
27     IA
28     TX
29     CA
       ..
470    MN
471    AR
472    CO
473    IL
474    NJ
475    CA
476    CA
477    KS
478    CA
479    UT
480    CA
481    FL
482    ID
483    CA
484    OR
485    CA
486    MS
487    ID
488    CA
489    CA
490    CA
491    CA
492    IN
493    OH
494    NC
495    NC
496    OH
497    CT
498    TX
499    CA
Name: StateAbbr, Length: 500, dtype: object